In [106]:
1+2

3

In [107]:
import numpy as np
#x=np.array([1,2,3,4])
#y=np.array([1,2,3,"4"]) #string en genel olduğundan array içerisindeki her şey string ifade olur
#z=np.array(["1",2,"3",4], dtype="int32") #dtype ile array elemanlarının tipi manuel ayarlanır
#w=np.zeros(10) #0lardan oluşan array (type belirtilmez ise default olarak float tanımlanır)
#m=np.zeros([3,8,8,5]) #8e8lik 0lardan oluşan array
#a=np.full([3,5],4)#kendi isteğimizin sayıyla belirlenen aralıkta array oluşturma
#b=np.arange(0,10) #ardışık array (,,sayı) ile sayı kadar arttırılmış ardışık array de oluşturulabilir
#c=np.arange(13,1,-3) 
#d=np.linspace(0,1)  #0 ila 1 arasında (default değer 50 olacak şekilde) 50 nokta üretir
#e=np.linspace(0,1,15) #son değeri değiştirerek kaç nokta üreteceğini belirleyebiliriz
#f=np.random.normal(0,1,(4,5)) #4e5lik 0 ortlamalı 1 standart sapması olan random 20 sayı üretme
#g=np.random.randint(0,10) #4e5lik 0 ila 10 arasındaki random 20 sayı üretme
#h=np.eye(3,3)# birim matris oluşturma
#a=np.array([1,2,3])
#b=np.array([2,4,6])
#print(a*b)# array matematiksel işlemler yapılabilir
#i=np.arange(1,11)
#print(i.size) #array boyutu
#print(i.ndim) #dimension
#print(i.dtype) #array type
#print(i.reshape(5,2)) #.reshape ile eleman sayısı tutması şartıyla array ile oynanabilir
#print(i.reshape(5,2).ndim) #row column ile oynanmış bir array in dimension ı değişebilir
#print(i[np.newaxis,:]) #ilave satır ekleme
#print(i[:,np.newaxis]) #ilave sütun ekleme
#print(np.concatenate([a,b]))#arrayleri listedeki mantık gibi birleştirme yapar
#print(np.concatenate([a,a],axis=1))# axis=1 yapılına altına ekler

#print(h)
#print(g)
#print(f)
#print(d)
#print(e)
#print(c)
#print(b)
#print(x)
#print(y)
#print(z)
#print(w)
#print(m)
#print(a)
"""def array(arr):
    new_arr=arr[::-1]
    return np.array(new_arr,float)
arr=numpy.array([1,2,3])
print(array(arr)) Hackerrank problemi"""
a=np.shape(input().split(' '))
a=np.array([input().split(' '),input().split(' ')],dtype="int32")
print(np.prod(np.sum(a,axis=0)))


1


In [108]:
import numpy as np
size=input().split(' ')
arr=np.array([input().split(' ') for _ in range(int(size[0]))],dtype="int32")

In [ ]:
import numpy as np
size=np.array(input().split(' '))
arr=np.array([input().split(' ') for _ in range(int(size[0]))],dtype="int32")
print(np.max(np.min(arr,axis=1)))

3


In [ ]:
import numpy as np
size = (input().split(' '))
size=(int(elm) for elm in size)
size=tuple(size)
print(np.zeros(size,dtype="int32"))
print(np.ones(size, dtype ="int32"))

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [ ]:
import numpy as np
size=input().split(' ')
np.set_printoptions(legacy='1.13')
print(np.eye(int(size[0]),int(size[1])))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [ ]:
import numpy as np
np.shape(input().split(' '))
A=np.array([input().split(' ')],dtype="int32")
B=np.array([input().split(' ')],dtype="int32")
print(np.add(A,B))
print(np.subtract(A,B))
print(np.multiply(A,B))
print(np.floor_divide(A,B))  
print(np.mod(A,B))
print(np.power(A,B))

[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [ ]:
import numpy as np
arr=input().split(' ')
arr=(float(elm) for elm in size)
arr=list(arr)
new_arr=np.array(arr)
print(new_arr)

[[ 1.1  2.2  3.3  4.4  5.5  6.6  7.7  8.8  9.9]]


In [25]:
import numpy as np
pol=np.array(input().split(' '),dtype=float)
x=input()
print (np.polyval(pol, int(x)))

3.0
